project:
  type: book

book:
  title: "VAR step by step review"
  author: "Daniele Marinello"
  date: today
  chapters:
    - index.qmd
    - preface.qmd
    - 01-what-is-var.qmd
    - 02-from-ar-to-var.qmd

format:
  html:
    theme: cosmo
    css: styles.css

